name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: "npm"
      - run: npm ci --legacy-peer-deps
        env:
          PACKAGES_PAT: ${{ secrets.PACKAGES_PAT }}

      - run: npm run lint

      - name: Deploy
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.JANEIRL_SSH_DEPLOY_KEY }}
        with:
          source-directory: '.'
          destination-github-username: JaneIRL
          destination-repository-username: JaneIRL
          destination-repository-name: 'hackuta2023-site'
          user-email: 103539883+JaneIRL@users.noreply.github.com
          target-branch: main
